# Generated by Django 5.2.6 on 2025-09-20 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_bodega', models.CharField(max_length=100)),
                ('numero_estanteria', models.CharField(max_length=50)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Retiro', 'Retiro')], max_length=50)),
                ('operario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.operario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('especificaciones', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estanteria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Pedido.estanteria')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('fecha_retiro', models.DateField(blank=True, null=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Pedido.historialmovimiento')),
                ('retiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pedido.historialmovimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.producto')),
            ],
        ),
    ]
