# Generated by Django 4.2.24 on 2025-12-04 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_total', models.FloatField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('num_cuenta', models.CharField(max_length=50)),
                ('comprobante', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='Pedido.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('estado', models.CharField(choices=[('Transito', 'Transito'), ('Alistamiento', 'Alistamiento'), ('Por verificar', 'Por verificar'), ('Rechazado x verificar', 'Rechazado x verificar'), ('Verificado', 'Verificado'), ('Empacado x despachar', 'Empacado x despachar'), ('Despachado', 'Despachado'), ('Despachado x facturar', 'Despachado x facturar'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Produccion', 'Produccion'), ('Bordado', 'Bordado'), ('Dropshipping', 'Dropshipping'), ('Compra', 'Compra'), ('Anulado', 'Anulado')], default='Alistamiento', max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('items', models.JSONField(blank=True, default=list)),
                ('operario', models.CharField(blank=True, max_length=100)),
                ('bodega_id', models.CharField(blank=True, max_length=100)),
                ('hash_de_integridad', models.CharField(blank=True, editable=False, max_length=64)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Pedido.cliente')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='Pedido.factura')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=100)),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_solicitados', to='Pedido.pedido')),
            ],
        ),
    ]
