# Generated by Django 4.2.24 on 2025-12-04 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_bodega', models.CharField(max_length=100)),
                ('numero_estanteria', models.CharField(max_length=50)),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='Pedido.bodega')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('costo_total', models.FloatField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('num_cuenta', models.CharField(max_length=50)),
                ('comprobante', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='Pedido.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operario_responsable', models.CharField(blank=True, max_length=100)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('tipo_movimiento', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Retiro', 'Retiro')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='Pedido.historialmovimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('estado', models.CharField(choices=[('Transito', 'Transito'), ('Alistamiento', 'Alistamiento'), ('Por verificar', 'Por verificar'), ('Rechazado x verificar', 'Rechazado x verificar'), ('Verificado', 'Verificado'), ('Empacado x despachar', 'Empacado x despachar'), ('Despachado', 'Despachado'), ('Despachado x facturar', 'Despachado x facturar'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Produccion', 'Produccion'), ('Bordado', 'Bordado'), ('Dropshipping', 'Dropshipping'), ('Compra', 'Compra'), ('Anulado', 'Anulado')], default='Alistamiento', max_length=30)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operario', models.CharField(blank=True, max_length=100)),
                ('hash_de_integridad', models.CharField(blank=True, editable=False, max_length=64)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='Pedido.cliente')),
                ('factura', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='Pedido.factura')),
                ('items', models.ManyToManyField(related_name='pedidos', to='Pedido.item')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('especificaciones', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estanteria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='Pedido.estanteria')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_solicitados', to='Pedido.producto')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Pedido.producto'),
        ),
        migrations.AddField(
            model_name='item',
            name='retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Pedido.historialmovimiento'),
        ),
    ]
