# Generated by Django 4.2.24 on 2025-09-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_alter_estanteria_bodega_alter_item_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
