# Generated by Django 4.2.24 on 2025-10-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0004_cliente_factura_pedido_productosolicitado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='Pedido.factura'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
