# Generated by Django 4.2.24 on 2025-10-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0007_pedido_operario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
