# Generated by Django 4.2.24 on 2025-11-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0009_merge_20251008_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='hash_de_integridad',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True),
        ),
    ]
