# Generated by Django 4.2.24 on 2025-09-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_rename_apellido_usuario_apellidos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='apellidos',
            new_name='apellido',
        ),
    ]
