# Generated by Django 4.2.24 on 2025-09-20 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
        ('Users', '0003_rename_apellidos_usuario_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operario',
            name='rol',
        ),
        migrations.AddField(
            model_name='operario',
            name='bodega',
            field=models.ManyToManyField(to='Inventario.bodega'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='Operario', max_length=50),
        ),
        migrations.CreateModel(
            name='JefeBodega',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Users.usuario')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Inventario.bodega')),
            ],
            bases=('Users.usuario',),
        ),
    ]
