# Generated by Django 4.2.24 on 2025-09-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_usuario_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
