# Generated by Django 4.2.24 on 2025-09-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_alter_usuario_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
