# Generated by Django 4.2.24 on 2025-09-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='fecha_retiro',
        ),
    ]
