# Generated by Django 4.2.24 on 2025-09-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0002_remove_item_fecha_retiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estanteria',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estanterias', to='Pedido.bodega'),
        ),
        migrations.AlterField(
            model_name='item',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Pedido.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estanteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='productos', to='Pedido.estanteria'),
        ),
    ]
