# Generated by Django 4.2.25 on 2025-10-02 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0003_alter_estanteria_bodega_alter_item_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('costo_total', models.FloatField()),
                ('metodo_pago', models.CharField(max_length=50)),
                ('num_cuenta', models.CharField(max_length=50)),
                ('comprobante', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='Pedido.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Transito', 'Transito'), ('Alistamiento', 'Alistamiento'), ('Por verificar', 'Por verificar'), ('Rechazado x verificar', 'Rechazado x verificar'), ('Verificado', 'Verificado'), ('Empacado x despachar', 'Empacado x despachar'), ('Despachado', 'Despachado'), ('Despachado x facturar', 'Despachado x facturar'), ('Entregado', 'Entregado'), ('Devuelto', 'Devuelto'), ('Produccion', 'Produccion'), ('Bordado', 'Bordado'), ('Dropshipping', 'Dropshipping'), ('Compra', 'Compra'), ('Anulado', 'Anulado')], default='Alistamiento', max_length=30)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='Pedido.factura')),
                ('items', models.ManyToManyField(related_name='pedidos', to='Pedido.item')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoSolicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pedido.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_solicitados', to='Pedido.producto')),
            ],
        ),
    ]
