# Generated by Django 4.2.24 on 2025-10-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_usuario_rol'),
        ('Pedido', '0006_pedido_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='operario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Users.operario'),
        ),
    ]
