# Generated by Django 4.2.24 on 2025-09-21 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
