# Generated by Django 4.2.24 on 2025-10-03 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pedido', '0007_pedido_operario'),
        ('Users', '0008_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bodega', models.ManyToManyField(to='Pedido.bodega')),
            ],
            options={
                'abstract': False,
            },
            bases=('Users.usuario',),
        ),
    ]
