# Generated by Django 4.2.24 on 2025-10-08 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_vendedor'),
        ('Users', '0010_alter_usuario_login'),
    ]

    operations = [
    ]
